set shell := ["powershell.exe", "-Command"]

default: fmt validate lint security test

validate:
    terraform init -backend=false
    terraform validate

fmt:
    terraform fmt -recursive

lint:
    tflint --recursive

security:
    tfsec .

test:
    terraform test
