name: Terraform apply (sandbox-gitops)
run-name: sandbox-apply-gitops

on:
  push:
    branches:
      - main
    paths:
      - infra-as-code/terraform/solutions/sandbox-gitops/**
      - infra-as-code/gitops/argocd/root.yaml

jobs:
  apply:
    uses: ./.github/workflows/_terraform-apply.yml
    with:
      environment: sbx
      solution: sandbox-gitops
    secrets: inherit
