name: Terraform Apply — Sandbox

on:
  push:
    branches: [main]
    paths:
      - "infra-as-code/terraform/solutions/sandbox/**"
      - "infra-as-code/terraform/modules/kubernetes/v2.0.0/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apply:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_terraform-apply.yml
    with:
      environment: sbx
      solution: sandbox
    secrets: inherit
